/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BerichtSjabloonRouteImport } from './routes/bericht-sjabloon'
import { Route as StyleguideRouteImport } from './routes/styleguide'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BerichtSjabloonRoute = BerichtSjabloonRouteImport.update({
  id: '/bericht-sjabloon',
  path: '/bericht-sjabloon',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bericht-sjabloon': typeof BerichtSjabloonRoute
  '/styleguide': typeof StyleguideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bericht-sjabloon': typeof BerichtSjabloonRoute
  '/styleguide': typeof StyleguideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bericht-sjabloon': typeof BerichtSjabloonRoute
  '/styleguide': typeof StyleguideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bericht-sjabloon' | '/styleguide'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bericht-sjabloon' | '/styleguide'
  id: '__root__' | '/' | '/bericht-sjabloon' | '/styleguide'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BerichtSjabloonRoute: typeof BerichtSjabloonRoute
  StyleguideRoute: typeof StyleguideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bericht-sjabloon': {
      id: '/bericht-sjabloon'
      path: '/bericht-sjabloon'
      fullPath: '/bericht-sjabloon'
      preLoaderRoute: typeof BerichtSjabloonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BerichtSjabloonRoute: BerichtSjabloonRoute,
  StyleguideRoute: StyleguideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
